"""add_ticket_type_column

Revision ID: 7202eddbd81a
Revises: 1561c563c5f9
Create Date: 2026-02-20 22:22:19.418230
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '7202eddbd81a'
down_revision: Union[str, None] = '1561c563c5f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy_requests', sa.Column('ticket_type', sa.String(length=100), nullable=True))
    op.add_column('sell_offers', sa.Column('ticket_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sell_offers', 'ticket_type')
    op.drop_column('buy_requests', 'ticket_type')
    # ### end Alembic commands ###
