"""add pending_confirmations table

Revision ID: db6f84ca11a6
Revises: 7202eddbd81a
Create Date: 2026-02-26 22:14:11.551140
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'db6f84ca11a6'
down_revision: Union[str, None] = '7202eddbd81a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_confirmations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sell_offer_id', sa.Integer(), nullable=False),
    sa.Column('buy_request_id', sa.Integer(), nullable=False),
    sa.Column('seller_phone', sa.String(length=20), nullable=False),
    sa.Column('buyer_phone', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'DECLINED', 'EXPIRED', name='confirmationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buy_request_id'], ['buy_requests.id'], ),
    sa.ForeignKeyConstraint(['sell_offer_id'], ['sell_offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_confirmations_buy_request_id'), 'pending_confirmations', ['buy_request_id'], unique=False)
    op.create_index(op.f('ix_pending_confirmations_sell_offer_id'), 'pending_confirmations', ['sell_offer_id'], unique=False)
    op.create_index(op.f('ix_pending_confirmations_seller_phone'), 'pending_confirmations', ['seller_phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_confirmations_seller_phone'), table_name='pending_confirmations')
    op.drop_index(op.f('ix_pending_confirmations_sell_offer_id'), table_name='pending_confirmations')
    op.drop_index(op.f('ix_pending_confirmations_buy_request_id'), table_name='pending_confirmations')
    op.drop_table('pending_confirmations')
    # ### end Alembic commands ###
